version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - postgres
      - beat
    volumes:
      - .:/app
    command: celery -A core.celery_app.celery worker --loglevel=info

  beat:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    command: celery -A core.celery_app.celery beat --loglevel=info

volumes:
  postgres_data: